# Generated by Django 4.1.1 on 2022-10-16 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0003_alter_device_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="type",
            field=models.CharField(
                choices=[
                    ("SM", "smartphone"),
                    ("TV", "tv"),
                    ("TB", "tablet"),
                    ("LP", "laptop"),
                    ("PC", "personal computer"),
                    ("WT", "watch"),
                    ("RT", "router"),
                ],
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="TelegramMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_msg_id", models.IntegerField()),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_network_messages",
                        to="collector.network",
                    ),
                ),
                (
                    "telegram_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_network_messages",
                        to="collector.telegramaccount",
                    ),
                ),
                (
                    "telegram_chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_network_messages",
                        to="collector.telegramchat",
                    ),
                ),
            ],
        ),
    ]
